<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 2017/9/1
 * Time: 19:52
 */

namespace app\modules\web\controllers\common;


use app\common\base\BaseController;
use app\common\services\Urlservice;
use app\models\Admin;

class BaseWebController extends BaseController{

    public $layout='main';
    public $current_user = null;
    public $allow_nullcookieurl = ['web/admin/login'];
    public function beforeAction($action){
        if(in_array($action->getUniqueId(),$this->allow_nullcookieurl)){
            return true;
        }
        if(!$this->cookieVerify()){
            if(\Yii::$app->request->isAjax){
                return json_encode([
                    'code' => -1,
                    'status'=> 'error',
                    'msg'  => '请先登录',
                ]);
            }
            return $this->redirect(Urlservice::buildWebUrl('/admin/login'));
        }
        return parent::beforeAction($action); //TODO: Change the autogenerated stub
    }

    public function cookieVerify(){
        $cookie_info = $this->get_cookie('user_login');

        if(!$cookie_info){
            return false;
        }
        list($user_info_md5,$adm_id) = explode('#',$cookie_info);
        $user_info = Admin::find()->where('adm_id='.$adm_id)->one();
        $user_verify = md5($user_info['adm_name'].md5($user_info['adm_pwd']));
        if($user_verify != $user_info_md5){
            return false;
        }
        $this->current_user = $user_info;

        \Yii::$app->view->params['current_user'] = $user_info;
        return true;

    }

}